/* 
  Sketch generated by the Arduino IoT Cloud Thing "KibbleBot"

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool dispense;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
  pinMode(D2, OUTPUT); // dir
  pinMode(D3, OUTPUT); // step
  pinMode(D4, OUTPUT); // sleep
  pinMode(D5, INPUT_PULLUP); // dispense button

  digitalWrite(D2, LOW);
  digitalWrite(D3, LOW);
  digitalWrite(D4, LOW);
  
  
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();

  // Check to see if the button has been pressed
  if (digitalRead(D5) == LOW) {
    dispenseKibbles();
  }
}

/*
  Since Dispense is READ_WRITE variable, onDispenseChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onDispenseChange()  {
  dispenseKibbles();
}

void dispenseKibbles() {
  digitalWrite(D4, HIGH); // disable sleep
  
  for (int i = 0; i <= 800; i++) {
    digitalWrite(D3, HIGH);
    delayMicroseconds(250);
    digitalWrite(D3, LOW);
    delayMicroseconds(250);
    
    if (i % 100 == 0) {
      digitalWrite(LED_BUILTIN, !digitalRead(LED_BUILTIN));
    }
  }
  
  digitalWrite(D4,LOW); // enable sleep
  digitalWrite(LED_BUILTIN, LOW); // turn off LED
}